services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: WIAMSB
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - backend-network
    depends_on:
      - db
  webserver:
    image: nginx:latest
    container_name: WIAMSB_webserver
    restart: unless-stopped
    ports:
      - "9000:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./storage:/var/www/storage
    depends_on:
      - app
    networks:
      - backend-network
  db:
    image: mysql:5.7
    container_name: WIAMSB_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: WIAMS
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: secret
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend-network
networks:
  backend-network:
    driver: bridge

volumes:
  db-data:
